### ISSUE TITLE
Unable to update firmware after updating klipper - mainsail 

### ISSUE THREAD

**Issue by midicdj1000** [MotorDynamicsLab/Leviathan#5]
I just flashed the Leviathan with klipper 11 and then told mainsail to update everything. Now I can't flash new firmware it says it can't find the usb port.

I press sw1 twice and the boot loader led flashed. 

Run the command to check it is showing 

pi@mainsailos:~ $ ls /dev/serial/by-id/*

/dev/serial/by-id/usb-katapult_stm32f446xx_1B0047000451313133353932-if00

I run the flash command
~/klippy-env/bin/python ~/katapult/scripts/flashtool.py -d /dev/ttyACM0 -f out/klipper.bin

and it gives this error

pi@mainsailos:~/klipper $ ~/klippy-env/bin/python ~/katapult/scripts/flashtool.py -d /dev/ttyACM0 -f out/klipper.bin
ERROR:root:Flash Error
Traceback (most recent call last):
  File "/home/pi/klippy-env/lib/python3.9/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/katapult/scripts/flashtool.py", line 543, in run
    serial_dev.open()
  File "/home/pi/klippy-env/lib/python3.9/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/katapult/scripts/flashtool.py", line 629, in main
    loop.run_until_complete(sock.run(args.device, args.baud, fpath))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/katapult/scripts/flashtool.py", line 545, in run
    raise FlashCanError("Unable to open serial port: %s" % (e,))
FlashCanError: Unable to open serial port: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
pi@mainsailos:~/klipper $

**Comment by midicdj1000** [comment]
With some help from the klipper discord this command worked

~/klippy-env/bin/python ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32f446xx_1B0047000451313133353932-if00 -f out/klipper.bin

it needed the full dev device instead of the ttyACM0

**Comment by camerony** [comment]
Can I get some more information?  What versions of the RPi are you using?  Also the OS version, Bookworm or Bullseye?

**Comment by midicdj1000** [comment]
![image](https://github.com/MotorDynamicsLab/Leviathan/assets/30492351/8f0ece7c-6ab8-45b6-b1ca-3aacd4304e94)

PI 3B+

How do I check for /dev/ttyACM0 ?

**Comment by camerony** [comment]
`ls /dev/tty*`

**Comment by midicdj1000** [comment]
![image](https://github.com/MotorDynamicsLab/Leviathan/assets/30492351/00c3f996-49d8-4d30-879e-db8f1860a1d8)

**Comment by midicdj1000** [comment]
how do you know what it's allocated to ?
something must have changed between the first flashing and all the upgrades.

**Comment by midicdj1000** [comment]
I forgot to show cmdline
![image](https://github.com/MotorDynamicsLab/Leviathan/assets/30492351/74b4b672-96cd-4398-b09d-aaae6ed2d9c6)

**Comment by camerony** [comment]
That is your USB port, not sure what happened.  But it should work with /dev/ttyACM0, if the Leviathan is the only device plugged in to the Rpi.

**Comment by midicdj1000** [comment]
It did work the first time before all the updates

**Comment by camerony** [comment]
Does it work now though?  I'll haven't been able to reproduce your issue, since /dev/ttyACM0 exists.

**Comment by midicdj1000** [comment]
and it does not program
![image](https://github.com/MotorDynamicsLab/Leviathan/assets/30492351/016a3e50-ceb3-4d87-bc48-ffe75efc3a08)

**Comment by midicdj1000** [comment]
if I change to ttyACM1 it programs ok
![image](https://github.com/MotorDynamicsLab/Leviathan/assets/30492351/253bd7fe-3c8a-4d9a-835d-87b1c6b0c2a8)

**Comment by camerony** [comment]
Ok, thanks.  Not sure why you're not getting /dev/ttyACM0 in bootloader mode.  But at least we confirmed it does work, just that it got reassigned as /dev/ttyACM1.     I'll see if can reproduce that.

**Comment by midicdj1000** [comment]
it would be a lot easier to use the /dev/serial/by-id/usb-katapult_stm32f446xx_1B0047000451313133353932-if00 with the unique id, you ask to check this is present so why not use it and save any potential problems with the ACM0

**Comment by camerony** [comment]
true, I'll add that is a second option.  Thanks for troubleshooting.

**Comment by midicdj1000** [comment]
Can you explain the USB, CAN and UART options at the start.
If I am using UART to talk to the PI will this stop me using CAN to connect to a toolhead board ?

I setup with USB to talk to the PI and want to use  CAN connect to a BTT board once I have everthing else setup.

**Comment by camerony** [comment]
I suggest you join https://discord.com/channels/692982154577313814/1180911286142369842   for that question.

**Comment by camerony** [comment]
<img width="445" alt="image" src="https://github.com/MotorDynamicsLab/Leviathan/assets/1082654/ee270683-b022-4fc7-9fde-ab0b66acc43f">
 
added addition command option
